### ISSUE TITLE
作者你好

### ISSUE THREAD

**Issue by xieguanliang** [zfeng217/5singAPI#1]
api/search  搜索功能，请求方式是post，你确定没写错吗， 我怎么都访问不到啊

**Comment by miaowing** [comment]
是post请求，可能是其他原因造成的，我查一下。

**Comment by miaowing** [comment]
header设置content-type: 'application/json'
body数据格式是json
在线demo：http://runjs.cn/code/xl4e77g4

**Comment by xieguanliang** [comment]
赞！
